### PR TITLE
Use PHP 5.4 as minimum and allow PHP 7

### PR DESCRIPTION
**Pull request by aimeos**
Traits are available since PHP 5.4

### CODE REVIEW

**Comment by judgej** [comment]
A few other things would need changing to meet this requirement:

* I don't think constructs such as `empty($this->getItems())` were allowed in 5.4, and we use that in one or two places (maybe just the one place).
* Class dereferencing `::class` is used a lot. Those would need to change to strings.

That's probably it.

**Comment by aimeos** [comment]
OK, then it's better to use "^5.5||^7.0"

**Comment by judgej** [comment]
Not saying it can't be done if you need PHP 5.4 It would just need to take some other considerations into account. We could branch off to a PHP 5.4/Omnipay 2.x version now, dropping PHP 7.x support for that, and keep the master branch on PHP 5.6+ (including 7.x) and move that towards Omnipay 3.x. That really depends on what your support needs are.

Could you explain "^5.5||^7.0"? Isn't that the same as just "^5.5"? I think even PHP 5,5 would need a lower (and drepcated) PHP Unit test suite, so would likely need to be a separate branch.

**Comment by judgej** [comment]
Mind, I may be mixing up the PHPUnit the package requests (through Omnipay 2.x) and the PHPUnit I have in my path, which will be a later version. Let me take another look and see what can be done.

**Comment by aimeos** [comment]
PHP 5.5 is OK. "^5.5" means all PHP 5 versions since 5.5.0 but not 6.x, 7.x or higher. Currently, you can't install the package if PHP 7 is installed

**Comment by judgej** [comment]
PHP Unit 3.7.38 is the one currently installed for this driver (via Omnipay tests ~2.0). This is testing okay for me on PHP 5.5, 5.6 and 7.1, but not 7.2

> PHP Fatal error:  Declaration of PHPUnit_Framework_Comparator_DOMDocument::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with PHPUnit_Framework_Comparator_Object::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in /.../vendor/phpunit/phpunit/PHPUnit/Framework/Comparator/DOMDocument.php on line 114

The two interfaces in question:

> assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false)
> assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array)

That may be a strict check that can be turned off, but will need to explore it later.

**Comment by judgej** [comment]
New release https://github.com/academe/omnipay-datatrans/releases/tag/2.0.6 made with the dependency updates. I still need to work out how to load multiple phpunit versions for different PHP versions. I think this would be a travis thing, setting up different PHP versions with different dependencies, rather than a core phpunit feature.

**Comment by aimeos** [comment]
You can find an example here: https://github.com/aimeos/aimeos-laravel/blob/master/.travis.yml

**Pull request closed without merging**
