### PR TITLE
fix wrong fields for auth request

### PR DESCRIPTION
**Pull request by Axent96**
Update AbstractRedirectRequest.php

### CODE REVIEW

**Comment by Axent96** [comment]
Issue #14

**Comment by Axent96** [comment]
@judgej doo you can please check it & release new version with the PR?

**Comment by judgej** [comment]
Thank you @Axent96 I'll take a look at this shortly.

**Comment by judgej** [comment]
Will tag when I've run some tests, but feel free to use `@dev' or `3c1647f81fdd6fa0963385f2d1e11feb4b722704` in the meantime.

**Comment by Axent96** [comment]
@judgej thank you a lot

**Pull request merged**
